# Use Node.js as the base image
FROM node:22-alpine

# Set working directory
WORKDIR /workspace

# Install global dependencies for Vue
RUN npm install -g @vue/cli

# Install global dependencies for Quasar
RUN npm i -g @quasar/cli
